# Generated by Django 3.2.6 on 2021-08-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
