# Generated by Django 3.2.6 on 2021-08-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210830_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=50)),
                ('username2', models.CharField(max_length=50)),
                ('date2', models.CharField(max_length=50)),
                ('concern', models.CharField(max_length=25)),
            ],
        ),
    ]
