# Generated by Django 3.2.6 on 2021-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_leave_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='concern',
            field=models.CharField(max_length=500),
        ),
    ]
