# Generated by Django 3.2.6 on 2021-09-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_leave_request_concern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='attendance2',
            field=models.DateField(),
        ),
    ]
