# Generated by Django 3.2.7 on 2021-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_employees_attendance2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='attendance2',
            field=models.CharField(max_length=50),
        ),
    ]
